export const defaultLabResults: any = {
    "% Hemoglobin A1c": {value: "", added: false},
    "Alanine Aminotransferase (ALT)": {value: "", added: false},
    "Albumin": {value: "", added: false},
    "Alkaline Phosphatase": {value: "", added: false},
    "Amylase": {value: "", added: false},
    "Anti-Nuclear Antibody": {value: "", added: false},
    "Asparate Aminotransferase (AST)": {value: "", added: false},
    "Bicarbonate": {value: "", added: false},
    "Bilirubin, Direct": {value: "", added: false},
    "Bilirubin, Total": {value: "", added: false},
    "C-Reactive Protein": {value: "", added: false},
    "Calcium, Total": {value: "", added: false},
    "Carcinoembyronic Antigen (CEA)": {value: "", added: false},
    "CD4 Absolute": {value: "", added: false},
    "CD4 Cells, Percent": {value: "", added: false},
    "Chloride": {value: "", added: false},
    "Cholesterol, HDL": {value: "", added: false},
    "Cholesterol, LDL, Calculated": {value: "", added: false},
    "Cholesterol, LDL, Measured": {value: "", added: false},
    "Cholesterol, Total": {value: "", added: false},
    "Creatine Kinase (CK)": {value: "", added: false},
    "Creatinine, Urine": {value: "", added: false},
    "Creatinine": {value: "", added: false},
    "Ferritin": {value: "", added: false},
    "Folate": {value: "", added: false},
    "FSH": {value: "", added: false},
    "Glucose": {value: "", added: false},
    "Granulocyte Count": {value: "", added: false},
    "HCG, Maternal Screening": {value: "", added: false},
    "Hematocrit": {value: "", added: false},
    "Hemoglobin": {value: "", added: false},
    "Hepatitis A Virus Antibody": {value: "", added: false},
    "Hepatitis B Surface Antibody": {value: "", added: false},
    "Hepatitis B Surface Antigen": {value: "", added: false},
    "Hepatitis B Virus Core Antibody": {value: "", added: false},
    "Hepatitis C Virus Antibody": {value: "", added: false},
    "HIV Antibody": {value: "", added: false},
    "Homocysteine": {value: "", added: false},
    "Human Chorionic Gonadotropin": {value: "", added: false},
    "INR(PT)": {value: "", added: false},
    "Iron": {value: "", added: false},
    "Lactate Dehydrogenase (LD)": {value: "", added: false},
    "Lipase": {value: "", added: false},
    "Magnesium": {value: "", added: false},
    "Phosphate": {value: "", added: false},
    "Platelet Count": {value: "", added: false},
    "Potassium":{value: "", added: false},
};